version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: localhost:33060
      WORDPRESS_DB_USER: wordpressuser
      WORDPRESS_DB_PASSWORD: wordpresspass
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress:/var/www/html

  db:
    ports:
      - 8081:3306
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
      MYSQL_ROOT_PASSWORD: mysqlrootpass
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
