version: '3.1'
services:
    wordpress:
        image: wordpress:latest
        volumes: 
            - ~/docker/wrdps/data:/var/www/html
        ports:
            - 8080:80
        restart: unless-stopped
        environment:
            WORDPRESS_DB_HOST=[wordpressdbhost]
            WORDPRESS_DB_USER=[wordpressdbuser]
            WORDPRESS_DB_PASSWORD=[wordpressdbpass]
            WORDPRESS_DB_NAME=wordpress
            
##############Configured Database through PHPmyadmin with MariaDB 10.6##############
     db:
        image: mariadb:10.6
        container_name: maria 
        restart: unless-stopped
        volumes:
            - ~/docker/maria/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=[mysqlrootpass]
            - MYSQL_USER=[mysqluser]
            - MYSQL_PASSWORD=[mysqlpass]
            - MYSQL_DATABASE=mariadb
        ports:
            - 3306:3306
        networks:
            - database
            
networks:
    database:
        driver: bridge
        external: true
