version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: [dbhostname]
      WORDPRESS_DB_USER: [wordpressuser]
      WORDPRESS_DB_PASSWORD: [wordpresspass]
      WORDPRESS_DB_NAME: [wordpressdb]
    volumes:
      - wordpress:/var/www/html

     db:
        image: mariadb:10.6
        container_name: maria 
        restart: unless-stopped
        volumes:
            - ~/docker/maria/data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=[mysqlrootpass]
            - MYSQL_USER=[mysqluser]
            - MYSQL_PASSWORD=[mysqlpass]
            - MYSQL_DATABASE=mariadb
        ports:
            - "3306:3306"
        networks:
            - database
            
networks:
    database:
        driver: bridge
        external: true
